name: mc_dio_wrapper
description: "A new Flutter package for Multicaret projects."
version: 0.0.3
homepage: https://multicaret.com

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  talker_dio_logger: ^4.4.1
  talker_flutter: ^4.4.1
  hive: ^2.2.3
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  uuid: ^4.5.1
  crypto: ^3.0.6
  recase: ^4.1.0
  path_provider: ^2.1.5
  path: ^1.9.0
  fluttertoast: ^8.2.8

dev_dependencies:
  test: ^1.25.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

